# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow locates REST API file contracts
# (Swagger or OpenAPI format, v2 and v3, JSON and YAML)
# and runs 200+ security checks on them using 42Crunch Security Audit technology.
#
# Documentation is located here: https://docs.42crunch.com/latest/content/tasks/integrate_github_actions.htm
#
# To use this workflow, you will need to complete the following setup steps.
#
# 1. Create a free 42Crunch account at https://platform.42crunch.com/register
#
# 2. Follow steps at https://docs.42crunch.com/latest/content/tasks/integrate_github_actions.htm
#    to create an API Token on the 42Crunch platform
#
# 3. Add a secret in GitHub as explained in https://docs.42crunch.com/latest/content/tasks/integrate_github_actions.htm,
#    store the 42Crunch API Token in that secret, and supply the secret's name as api-token parameter in this workflow
#
# If you have any questions or need help contact https://support.42crunch.com

name: "new-feature-workflow"

# follow standard Code Scanning triggers
on: 
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]

env:
  PLATFORM_URL: https://demolabs.42crunch.cloud
  PLATFORM_SERVICE_ENDPOINT: services.demolabs.42crunch.cloud:8001

permissions:
  contents: read

jobs:
  rest-api-security-testing:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for 42Crunch/api-security-audit-action to upload results to Github Code Scanning
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: 42crunch-api-testing
        uses: 42Crunch/api-security-audit-action@v3
        with:
          # Please create free account at https://platform.42crunch.com/register
          # Follow these steps to configure API_TOKEN https://docs.42crunch.com/latest/content/tasks/integrate_github_actions.htm
          api-token: ${{ secrets.API_TOKEN }}
          # Fail if any OpenAPI file scores lower than 75
          min-score: 70
          platform-url: https://demolabs.42crunch.cloud
          default-collection-name: Code-Scanning-Import
          # Upload results to Github code scanning
          upload-to-code-scanning: true
          # Github token for uploading the results
          github-token: ${{ github.token }}

  run_conformance_scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read # for actions/checkout to fetch code
    steps:
      - name: Dynamic API testing
        uses: fjogeleit/http-request-action@v1
        with:
          url: https://photo-demo.westeurope.cloudapp.azure.com/scand/api/job
          method: POST
          contentType: "application/json"
          customHeaders: '{"Accept": "application/json"}'
          data: '{"token": "${{ secrets.SCAN_TOKEN }}","name": "scand-${{ github.run_id }}","platformService": "${{ env.PLATFORM_SERVICE_ENDPOINT }}","scandImage": "42crunch/scand-agent:v2.0.0-rc04","expirationTime": 600,"env": { "SCAN42C_host": "https://photo-demo.westeurope.cloudapp.azure.com/version1/api","SCAN42C_user": "user-inbound@acme.com","SCAN42C_pass": "${{ secrets.USER_PASS }}"}}'
          


    